[package]
name = "axia-network-bridge"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.21"
tracing = "0.1.29"
axia-primitives = { path = "../../../primitives" }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-consensus = { git = "https://github.com/axtend/axlib", branch = "axlib" }
axia-subsystem = { package = "axia-node-subsystem", path = "../../subsystem" }
axia-overseer = { path = "../../overseer" }
axia-node-network-protocol = { path = "../protocol" }
axia-node-subsystem-util = { path = "../../subsystem-util"}
parking_lot = "0.11.1"

[dev-dependencies]
assert_matches = "1.4.0"
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "axlib" }
futures-timer = "3"
axia-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
