[package]
name = "axia-availability-distribution"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
tracing = "0.1.29"
parity-scale-codec = { version = "2.3.1", features = ["std"] }
axia-primitives = { path = "../../../primitives" }
axia-erasure-coding = { path = "../../../erasure-coding" }
axia-subsystem = { package = "axia-node-subsystem", path = "../../subsystem" }
axia-node-network-protocol = { path = "../../network/protocol" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-node-primitives = { path = "../../primitives" }
sp-core = { git = "https://github.com/purestake/substrate", features = ["std"] , branch = "moonbeam-axia-v0.9.17" }
sp-keystore = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
thiserror = "1.0.30"
rand = "0.8.3"
derive_more = "0.99.17"
lru = "0.7.2"

[dev-dependencies]
axia-subsystem-testhelpers = { package = "axia-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/purestake/substrate", features = ["std"] , branch = "moonbeam-axia-v0.9.17" }
sp-keyring = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-tracing = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-network = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
axia-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
