{
 "title": "Kusama Validators Overview",
 "description": "Monitors deployed versions, warnings and errors logged.",
 "tags": [
  "Kusama",
  "Loki",
  "Logs"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "axia_build_info{chain=\"$chain\"}"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "axia_sync_peers{chain=\"$chain\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Versions",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc  (count by (version) (axia_build_info{chain=\"kusama\", instance=~\".*validator.*\"}))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Warnings / h / target",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"WARN\"} [1h])) by (target)",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  {
   "title": "Errors / h / target",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"ERROR\"} [1h])) by (target)",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  { "title": "Validator versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Versions",
   "type": "bargauge",
   "description": "Version information for all nodes.",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc  (count by (version) (axia_build_info{chain=\"kusama\", instance=~\".*validator.*\"}))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Node versions ",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "axia_build_info{instance=~\".*validator.*\",chain=\"kusama\"}"
    }
   ]
  },
  { "title": "Warnings and errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "All warnings / hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "warnings/h" } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"WARN\"} [1h])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Parachain warnings/hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "warnings/h" } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"WARN\", target=\"parachain\"}[1h])) by (subtarget)",
     "legendFormat": "{{subtarget}}"
    }
   ]
  },
  {
   "title": "All errors / hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "warnings/h" } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"ERROR\"} [1h])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Parachain errors/hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "warnings/h" } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"kusama-validator.*\", level=\"ERROR\", target=\"parachain\"}[1h])) by (subtarget)",
     "legendFormat": "{{subtarget}}"
    }
   ]
  }
 ]
}