[package]
name = "xcm-simulator-fuzzer"
version = "0.9.9"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Examples of xcm-simulator usage."
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
honggfuzz = "0.5.54"
scale-info = { version = "1.0", features = ["derive"] }

frame-system = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
frame-support = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
pallet-balances = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-std = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-io = { git = "https://github.com/axtend/axlib", branch = "16d1466" }

xcm = { path = "../../" }
xcm-simulator = { path = "../" }
xcm-executor = { path = "../../xcm-executor" }
xcm-builder = { path = "../../xcm-builder" }
pallet-xcm = { path = "../../pallet-xcm" }
polkadot-core-primitives = { path = "../../../core-primitives" }
polkadot-runtime-parachains = { path = "../../../runtime/parachains" }
polkadot-parachain = { path = "../../../parachain" }

[[bin]]
path = "src/fuzz.rs"
name = "xcm-fuzzer"
