[package]
name = "relay-rialto-allychain-client"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
relay-parity-client = { path = "../client-axlib" }
relay-utils = { path = "../utils" }

# Bridge dependencies

bp-rialto = { path = "../../primitives/chain-rialto" }
rialto-allychain-runtime = { path = "../../bin/rialto-allychain/runtime" }

# Axlib Dependencies

frame-system = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
frame-support = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
pallet-transaction-payment = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
