[package]
name = "relay-rialto-allychain-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
relay-substrate-client = { path = "../client-substrate" }
relay-utils = { path = "../utils" }

# Bridge dependencies

bp-rialto = { path = "../../primitives/chain-rialto" }
rialto-allychain-runtime = { path = "../../bin/rialto-allychain/runtime" }

# Substrate Dependencies

frame-system = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
frame-support = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
pallet-transaction-payment = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
