[package]
name = "pallet-shift-session-manager"
description = "A Axlib Runtime module that selects 2/3 of initial validators for every session"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Axlib Dependencies

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-staking = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

[dev-dependencies]
sp-core = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"scale-info/std",
	"sp-staking/std",
	"sp-std/std",
]
