[package]
name = "axia-node-core-pvf"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[[bin]]
name = "puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
always-assert = "0.1"
async-std = { version = "1.10.0", features = ["attributes"] }
async-process = "1.3.0"
assert_matches = "1.4.0"
futures = "0.3.21"
futures-timer = "3.0.2"
slotmap = "1.0"
tracing = "0.1.29"
pin-project = "1.0.9"
rand = "0.8.3"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
axia-allychain = { path = "../../../allychain" }
axia-core-primitives = { path = "../../../core-primitives" }
axia-node-subsystem-util = { path = "../../subsystem-util"}
sc-executor = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-executor-wasmtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-executor-common = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-externalities = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-io = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-wasm-interface = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-maybe-compressed-blob = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-tracing = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

[dev-dependencies]
adder = { package = "test-allychain-adder", path = "../../../allychain/test-allychains/adder" }
halt = { package = "test-allychain-halt", path = "../../../allychain/test-allychains/halt" }
hex-literal = "0.3.4"
tempfile = "3.2.0"
