[package]
name = "axia-gossip-support"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
sp-application-crypto = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sc-network = { git = "https://github.com/axtend/axlib", branch = "axlib" }

axia-node-network-protocol = { path = "../protocol" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-primitives = { path = "../../../primitives" }

futures = "0.3.21"
futures-timer = "3.0.2"
rand = { version = "0.8.3", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
tracing = "0.1.29"

[dev-dependencies]
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-consensus-babe = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-tracing = { git = "https://github.com/axtend/axlib", branch = "axlib" }

axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = "0.1.52"
lazy_static = "1.4.0"
