[package]
name = "rialto-bridge-node"
description = "Substrate node compatible with Rialto runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
jsonrpc-core = "15.1.0"
structopt = "0.3.21"
serde_json = "1.0.59"

# Bridge dependencies

bp-messages = { path = "../../../primitives/messages" }
bp-runtime = { path = "../../../primitives/runtime" }
bp-rialto = { path = "../../../primitives/chain-rialto" }
pallet-bridge-messages = { path = "../../../modules/messages" }
rialto-runtime = { path = "../runtime" }

# Substrate Dependencies


frame-benchmarking = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
frame-benchmarking-cli = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
node-inspect = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
pallet-transaction-payment-rpc = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-basic-authorship = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-cli = { git = "https://github.com/axtend/axlib", features = ["wasmtime"] , branch = "16d1466" }
sc-client-api = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-consensus = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-consensus-aura = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-executor = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-finality-grandpa = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-finality-grandpa-rpc = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-keystore = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-rpc = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-service = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-telemetry = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sc-transaction-pool = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-consensus = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-consensus-aura = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-finality-grandpa = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-inherents = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-timestamp = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
substrate-frame-rpc-system = { git = "https://github.com/axtend/axlib", branch = "16d1466" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
frame-benchmarking-cli = { git = "https://github.com/axtend/axlib", branch = "16d1466" }

[features]
default = []
runtime-benchmarks = [
	"rialto-runtime/runtime-benchmarks",
]
