[package]
name = "axlib-relay-helper"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
anyhow = "1.0"
thiserror = "1.0.26"
async-std = "1.9.0"
async-trait = "0.1.42"
codec = { package = "parity-scale-codec", version = "2.2.0" }
futures = "0.3.12"
num-traits = "0.2"
log = "0.4.14"


# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bridge-runtime-common = { path = "../../bin/runtime-common" }

finality-grandpa = { version = "0.14.0" }
finality-relay = { path = "../finality" }
relay-utils = { path = "../utils" }
messages-relay = { path = "../messages" }
relay-axlib-client = { path = "../client-substrate" }

pallet-bridge-messages = { path = "../../modules/messages" }

bp-runtime = { path = "../../primitives/runtime" }
bp-messages = { path = "../../primitives/messages" }

# Axlib Dependencies

frame-support = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-finality-grandpa = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "axlib" }

[dev-dependencies]
bp-millau = { path = "../../primitives/chain-millau" }
bp-betanet = { path = "../../primitives/chain-betanet" }
bp-wococo = { path = "../../primitives/chain-wococo" }
relay-betanet-client = { path = "../client-betanet" }
relay-wococo-client = { path = "../client-wococo" }
rialto-runtime = { path = "../../bin/rialto/runtime" }
