[package]
name = "test-allychain-halt"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test allychain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

[features]
default = [ "std" ]
std = []
