version: '3.5'
services:
  bridges-ui:
    image: axiatech/axia-bridges-ui
    environment:
      VIRTUAL_HOST: ui.brucke.link
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ui.brucke.link
      LETSENCRYPT_EMAIL: admin@axia.io
      CHAIN_1_AXLIB_PROVIDER: ${UI_CHAIN_1:-ws://localhost:9944}
      CHAIN_2_AXLIB_PROVIDER: ${UI_CHAIN_2:-ws://localhost:19944}
    ports:
      - "8080:80"
