[package]
name = "xcm-simulator"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test kit to simulate cross-chain message passing and XCM execution"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
paste = "1.0.6"

frame-support = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-io = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-std = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
axia-core-primitives = { path = "../../core-primitives"}
axia-allychain = { path = "../../allychain" }
axia-runtime-allychains = { path = "../../runtime/allychains" }
