[package]
name = "xcm-simulator"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
description = "Test kit to simulate cross-chain message passing and XCM execution"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
paste = "1.0.6"

frame-support = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-io = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-std = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
polkadot-core-primitives = { path = "../../core-primitives"}
polkadot-allychain = { path = "../../allychain" }
polkadot-runtime-allychains = { path = "../../runtime/allychains" }
