[package]
name = "bridge-runtime-common"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/axiatech/axia-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive"] }
ed25519-dalek = { version = "1.0", default-features = false, optional = true }
hash-db = { version = "0.15.2", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Bridge dependencies

bp-message-dispatch = { path = "../../primitives/message-dispatch", default-features = false }
bp-messages = { path = "../../primitives/messages", default-features = false }
bp-runtime = { path = "../../primitives/runtime", default-features = false }
pallet-bridge-dispatch = { path = "../../modules/dispatch", default-features = false }
pallet-bridge-grandpa = { path = "../../modules/grandpa", default-features = false }
pallet-bridge-messages = { path = "../../modules/messages", default-features = false }

# Substrate dependencies

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
pallet-transaction-payment = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
sp-state-machine = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "axlib" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
sp-trie = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }

[features]
default = ["std"]
std = [
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"hash-db/std",
	"scale-info/std",
	"pallet-bridge-dispatch/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"ed25519-dalek/u64_backend",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-state-machine",
]
