[package]
name = "storage-proof-fuzzer"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.54"
log = "0.4.0"
env_logger = "0.8.3"

# Bridge Dependencies

bp-runtime = { path = "../../primitives/runtime" }

# Substrate Dependencies

sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-state-machine = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-std = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-trie = { git = "https://github.com/axtend/axlib", branch = "axlib" }
