[package]
name = "axia-node-core-bitfield-signing"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
tracing = "0.1.29"
axia-primitives = { path = "../../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
wasm-timer = "0.2.5"
thiserror = "1.0.30"

[dev-dependencies]
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "axia-primitives-test-helpers", path = "../../../primitives/test-helpers" }
