[package]
name = "bp-messages"
description = "Primitives of messages module."
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
bitvec = { version = "0.20", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "bit-vec"] }
impl-trait-for-tuples = "0.2"
scale-info = { version = "1.0", default-features = false, features = ["bit-vec", "derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Bridge dependencies

bp-runtime = { path = "../runtime", default-features = false }

# Axlib Dependencies

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }

[features]
default = ["std"]
std = [
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-std/std",
]
