[package]
name = "axia-dispute-distribution"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
tracing = "0.1.29"
derive_more = "0.99.17"
parity-scale-codec = { version = "2.3.1", features = ["std"] }
axia-primitives = { path = "../../../primitives" }
axia-erasure-coding = { path = "../../../erasure-coding" }
axia-subsystem = { package = "axia-node-subsystem", path = "../../subsystem" }
axia-node-network-protocol = { path = "../../network/protocol" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-node-primitives = { path = "../../primitives" }
sc-network = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-application-crypto = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
thiserror = "1.0.30"
lru = "0.7.2"

[dev-dependencies]
async-trait = "0.1.52"
axia-subsystem-testhelpers = { package = "axia-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-tracing = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sc-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"
axia-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
