[package]
name = "rialto-allychain-runtime"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
homepage = "https://axlib.dev"
repository = "https://github.com/axiatech/axia-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

[dependencies]
codec = { package = 'axia-scale-codec', version = '2.0.0', default-features = false, features = ['derive']}
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = '1.0', optional = true, features = ['derive'] }

# Bridge depedencies

bp-rialto-allychain = { path = "../../../primitives/chain-rialto-allychain", default-features = false }

# Axlib Dependencies
## Axlib Primitive Dependencies
sp-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-block-builder = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-consensus-aura = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-inherents = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-io = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-offchain = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-transaction-pool = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-version = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

## Axlib FRAME Dependencies
frame-executive = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
frame-support = { git = "https://github.com/axtend/axlib", default-features = false, branch = "c92f69d" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
frame-system-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

## Axlib Pallet Dependencies
pallet-aura = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-balances = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-randomness-collective-flip = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-sudo = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-timestamp = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

# Cumulus Dependencies
cumulus-pallet-aura-ext = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-pallet-allychain-system = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-pallet-dmp-queue = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-pallet-xcm = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-pallet-xcmp-queue = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-primitives-core = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-primitives-timestamp = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
cumulus-primitives-utility = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }
allychain-info = { git = "https://github.com/axiatech/cumulus", branch = "master", default-features = false }

# Axia Dependencies
polkadot-allychain = { git = "https://github.com/axiatech/polkadot", branch = "master", default-features = false }
xcm = { git = "https://github.com/axiatech/polkadot", branch = "master", default-features = false }
xcm-builder = { git = "https://github.com/axiatech/polkadot", branch = "master", default-features = false }
xcm-executor = { git = "https://github.com/axiatech/polkadot", branch = "master", default-features = false }
pallet-xcm = { git = "https://github.com/axiatech/polkadot", branch = "master", default-features = false }

[features]
default = ['std']
runtime-benchmarks = [
	'sp-runtime/runtime-benchmarks',
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
]
std = [
	"bp-rialto-allychain/std",
	"codec/std",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"allychain-info/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-allychain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"cumulus-primitives-utility/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"pallet-aura/std",
	"sp-consensus-aura/std",
]
