[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "betanet-local"
command = "axia"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]

[[allychains]]
id = 100
addToGenesis = false

  [allychains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
