[package]
name = "axctest-runtime-constants"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
smallvec = "1.6.1"

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }
primitives = { package = "axia-primitives", path = "../../../primitives", default-features = false }
runtime-common = { package = "axia-runtime-common", path = "../../common", default-features = false }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "axlib" }

[features]
default = ["std"]
std = [
	"sp-runtime/std"
]
