[package]
name = "axia-approval-distribution"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
axia-node-primitives = { path = "../../primitives" }
axia-node-network-protocol = { path = "../protocol" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-primitives = { path = "../../../primitives" }

futures = "0.3.21"
tracing = "0.1.29"

[dev-dependencies]
sp-core = { git = "https://github.com/axtend/axlib", features = ["std"] , branch = "c92f69d" }

axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
schnorrkel = { version = "0.9.1", default-features = false }
rand_core = "0.5.1" # should match schnorrkel
env_logger = "0.9.0"
log = "0.4.13"
