[package]
name = "relay-axctest-client"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0" }
relay-parity-client = { path = "../client-axlib" }
relay-utils = { path = "../utils" }
scale-info = { version = "1.0", features = ["derive"] }

# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-axctest = { path = "../../primitives/chain-axctest" }
bp-message-dispatch = { path = "../../primitives/message-dispatch" }
bp-messages = { path = "../../primitives/messages" }
bp-polkadot = { path = "../../primitives/chain-polkadot" }
bp-polkadot-core = { path = "../../primitives/polkadot-core" }
bp-runtime = { path = "../../primitives/runtime" }
bridge-runtime-common = { path = "../../bin/runtime-common" }
pallet-bridge-dispatch = { path = "../../modules/dispatch" }

# Axlib Dependencies

frame-support = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
