[package]
name = "bp-rialto-parachain"
description = "Primitives of Rialto parachain runtime."
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]

# Bridge Dependencies

bp-messages = { path = "../messages", default-features = false }
bp-runtime = { path = "../runtime", default-features = false }

# Substrate Based Dependencies

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

[features]
default = ["std"]
std = [
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
