[package]
name = "pallet-bridge-grandpa"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
finality-grandpa = { version = "0.14.4", default-features = false }
log = { version = "0.4.14", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }

# Bridge Dependencies

bp-runtime = { path = "../../primitives/runtime", default-features = false }
bp-header-chain = { path = "../../primitives/header-chain", default-features = false }

# Substrate Dependencies

frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }
sp-finality-grandpa = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }
sp-trie = { git = "https://github.com/axtend/axlib", default-features = false , branch = "16d1466" }

# Optional Benchmarking Dependencies
bp-test-utils = { path = "../../primitives/test-utils", default-features = false, optional = true }
frame-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "16d1466" }

[dev-dependencies]
sp-io = { git = "https://github.com/axtend/axlib", branch = "16d1466" }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	"codec/std",
	"finality-grandpa/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"num-traits/std",
	"scale-info/std",
	"serde",
	"sp-finality-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"bp-test-utils",
	"frame-benchmarking",
]
