[package]
name = "axlib-relay"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
anyhow = "1.0"
async-std = "1.9.0"
codec = { package = "parity-scale-codec", version = "2.2.0" }
futures = "0.3.12"
hex = "0.4"
log = "0.4.14"
num-format = "0.4"
num-traits = "0.2"
paste = "1.0"
rand = "0.8"
structopt = "0.3"
strum = { version = "0.21.0", features = ["derive"] }

# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-axctest = { path = "../../primitives/chain-axctest" }
bp-messages = { path = "../../primitives/messages" }
bp-message-dispatch = { path = "../../primitives/message-dispatch" }
bp-millau = { path = "../../primitives/chain-millau" }
bp-axia = { path = "../../primitives/chain-axia" }
bp-rialto = { path = "../../primitives/chain-rialto" }
bp-rialto-allychain = { path = "../../primitives/chain-rialto-allychain" }
bp-betanet = { path = "../../primitives/chain-betanet" }
bp-token-swap = { path = "../../primitives/token-swap" }
bp-wococo = { path = "../../primitives/chain-wococo" }
bp-runtime = { path = "../../primitives/runtime" }
bp-alphanet = { path = "../../primitives/chain-alphanet" }
bridge-runtime-common = { path = "../../bin/runtime-common" }
finality-relay = { path = "../finality" }
messages-relay = { path = "../messages" }
millau-runtime = { path = "../../bin/millau/runtime" }
pallet-bridge-dispatch = { path = "../../modules/dispatch" }
pallet-bridge-messages = { path = "../../modules/messages" }
pallet-bridge-token-swap = { path = "../../modules/token-swap" }
relay-axctest-client = { path = "../client-axctest" }
relay-millau-client = { path = "../client-millau" }
relay-axia-client = { path = "../client-axia" }
relay-rialto-client = { path = "../client-rialto" }
relay-rialto-allychain-client = { path = "../client-rialto-allychain" }
relay-betanet-client = { path = "../client-betanet" }
relay-wococo-client = { path = "../client-wococo" }
relay-axlib-client = { path = "../client-axlib" }
relay-utils = { path = "../utils" }
relay-alphanet-client = { path = "../client-alphanet" }
rialto-allychain-runtime = { path = "../../bin/rialto-allychain/runtime" }
rialto-runtime = { path = "../../bin/rialto/runtime" }
axlib-relay-helper = { path = "../lib-axlib-relay" }

# Axlib Dependencies

frame-support = { git = "https://github.com/axtend/axlib", branch = "axlib" }
pallet-balances = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-io = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-version = { git = "https://github.com/axtend/axlib", branch = "axlib" }

# Axia Dependencies

axia-allychain = { git = "https://github.com/paritytech/axia", branch = "master" }
axia-primitives = { git = "https://github.com/paritytech/axia", branch = "master" }
axia-runtime-common = { git = "https://github.com/paritytech/axia", branch = "master" }
axia-runtime-allychains = { git = "https://github.com/paritytech/axia", branch = "master" }

[dev-dependencies]
hex-literal = "0.3"
pallet-bridge-grandpa = { path = "../../modules/grandpa" }
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "axlib" }
tempfile = "3.2"
finality-grandpa = { version = "0.14.0" }
