[package]
name = "rialto-runtime"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
homepage = "https://axlib.dev"
repository = "https://github.com/axiatech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive"] }
hex-literal = "0.3"
libsecp256k1 = { version = "0.7", optional = true, default-features = false, features = ["hmac"] }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Bridge dependencies

bp-header-chain = { path = "../../../primitives/header-chain", default-features = false }
bp-message-dispatch = { path = "../../../primitives/message-dispatch", default-features = false }
bp-messages = { path = "../../../primitives/messages", default-features = false }
bp-millau = { path = "../../../primitives/chain-millau", default-features = false }
bp-rialto = { path = "../../../primitives/chain-rialto", default-features = false }
bp-runtime = { path = "../../../primitives/runtime", default-features = false }
bridge-runtime-common = { path = "../../runtime-common", default-features = false }
pallet-bridge-dispatch = { path = "../../../modules/dispatch", default-features = false }
pallet-bridge-grandpa = { path = "../../../modules/grandpa", default-features = false }
pallet-bridge-messages = { path = "../../../modules/messages", default-features = false }
pallet-shift-session-manager = { path = "../../../modules/shift-session-manager", default-features = false }

# Axlib Dependencies

beefy-primitives = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
frame-executive = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-authority-discovery = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-babe = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-balances = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-beefy = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-beefy-mmr = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-grandpa = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-mmr = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-mmr-primitives = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-sudo = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-timestamp = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-authority-discovery = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-block-builder = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-consensus-babe = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-finality-grandpa = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-inherents = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-io = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-offchain = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-transaction-pool = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-trie = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-version = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

# Axia (allychain) Dependencies

axia-primitives = { git = "https://github.com/axia-tech/axia", branch = "master", default-features = false }
axia-runtime-common = { git = "https://github.com/axia-tech/axia", branch = "master", default-features = false }
axia-runtime-allychains = { git = "https://github.com/axia-tech/axia", branch = "master", default-features = false }

[dev-dependencies]
libsecp256k1 = { version = "0.7", features = ["hmac"] }

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

[features]
default = ["std"]
std = [
	"beefy-primitives/std",
	"bp-header-chain/std",
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-millau/std",
	"bp-rialto/std",
	"bp-runtime/std",
	"bridge-runtime-common/std",
	"codec/std",
	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"log/std",
	"pallet-authority-discovery/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-beefy/std",
	"pallet-beefy-mmr/std",
	"pallet-bridge-dispatch/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-grandpa/std",
	"pallet-mmr/std",
	"pallet-mmr-primitives/std",
	"pallet-shift-session-manager/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"axia-primitives/std",
	"axia-runtime-common/std",
	"axia-runtime-allychains/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-trie/std",
	"sp-version/std",
]
runtime-benchmarks = [
	"bridge-runtime-common/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"libsecp256k1",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
