[package]
name = "axia-node-core-allychains-inherent"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
tracing = "0.1.29"
thiserror = "1.0.30"
async-trait = "0.1.52"
axia-node-subsystem = { path = "../../subsystem" }
axia-primitives = { path = "../../../primitives" }
sp-blockchain = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-inherents = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "axlib" }
