[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "wococo-local"
command = "axia"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lallychain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--bob", "-lallychain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "--charlie", "-lallychain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  command = "/usr/local/bin/malus dispute-ancestor"
  extra_args = ["--dave", "-lallychain=debug"]
  image = "{{MALUS_IMAGE}}"
  autoConnectApi = false

[[allychains]]
id = 100

  [allychains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"
  args = ["-lallychain=debug"]
