[package]
name = "remote-ext-tests-bags-list"
version = "0.9.12"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
polkadot-runtime = { version = "0.9.8", path = "../../../runtime/polkadot" }
kusama-runtime = { version = "0.9.8", path = "../../../runtime/kusama" }

pallet-staking = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
pallet-election-provider-multi-phase = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
pallet-bags-list = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
frame-election-provider-support = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-storage = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-tracing = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-runtime = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
sp-std = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
frame-support = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
remote-externalities = { git = "https://github.com/axtend/axlib", branch = "16d1466" }
tokio = { version = "1", features = ["macros"] }
log = { version = "0.4.14" }
structopt = {version = "0.3.23" }
