[package]
name = "remote-ext-tests-bags-list"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
axia-runtime = { version = "0.9.17", path = "../../../runtime/axia" }
kusama-runtime = { version = "0.9.17", path = "../../../runtime/kusama" }
westend-runtime = { version = "0.9.17", path = "../../../runtime/westend" }
axia-runtime-constants = { version = "0.9.17", path = "../../../runtime/axia/constants" }
kusama-runtime-constants = { version = "0.9.17", path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { version = "0.9.17", path = "../../../runtime/westend/constants" }

pallet-bags-list-remote-tests = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-tracing = { git = "https://github.com/axtend/axlib", branch = "axlib" }
frame-system = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }

clap = { version = "3.0", features = ["derive"] }
log = "0.4.14"
tokio = { version = "1", features = ["macros"] }
