[package]
name = "test-allychain-halt"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
description = "Test allychain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

[features]
default = [ "std" ]
std = []
