[package]
name = "axia-node-core-approval-voting"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["bit-vec", "derive"] }
tracing = "0.1.29"
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
lru = "0.7"
merlin = "2.0"
schnorrkel = "0.9.1"
kvdb = "0.10.0"
derive_more = "0.99.17"

axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-overseer = { path = "../../overseer" }
axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-jaeger = { path = "../../jaeger" }

sc-keystore = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-consensus = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-consensus-slots = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-application-crypto = { git = "https://github.com/axtend/axlib", default-features = false, features = ["full_crypto"] , branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

[dev-dependencies]
parking_lot = "0.11.1"
rand_core = "0.5.1" #                                                                       should match schnorrkel
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-consensus-babe = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
kvdb-memorydb = "0.10.0"
test-helpers = { package = "axia-primitives-test-helpers", path = "../../../primitives/test-helpers" }
