[package]
name = "axia-node-network-protocol"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
async-trait = "0.1.52"
axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-jaeger = { path = "../../jaeger" }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sc-authority-discovery = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
strum = { version = "0.23", features = ["derive"] }
derive_more = "0.99.17"
futures = "0.3.21"
thiserror = "1.0.30"
