[package]
name = "axctest-runtime"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.136", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"
smallvec = "1.6.1"

authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
beefy-primitives = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
axctest-runtime-constants = { package = "axctest-runtime-constants", path = "./constants", default-features = false }
sp-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
inherents = { package = "sp-inherents", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
offchain-primitives = { package = "sp-offchain", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-std = { package = "sp-std", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-arithmetic = { package = "sp-arithmetic", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-io = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-staking = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-version = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
tx-pool-api = { package = "sp-transaction-pool", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
block-builder-api = { package = "sp-block-builder", git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
sp-npos-elections = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

pallet-authority-discovery = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-authorship = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-babe = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-bags-list = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-balances = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-bounties = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-collective = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-democracy = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-elections-phragmen = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-election-provider-multi-phase = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-executive = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-grandpa = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-gilt = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-identity = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-im-online = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-indices = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-membership = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-mmr-primitives = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-multisig = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-nicks = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-offences = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-preimage = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-proxy = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-recovery = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-scheduler = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-session = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-society = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-staking = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-staking-reward-fn = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system = {git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
frame-system-rpc-runtime-api = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-timestamp = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-tips = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-treasury = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-utility = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-vesting = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }
pallet-xcm = { path = "../../xcm/pallet-xcm", default-features = false }
frame-election-provider-support = { git = "https://github.com/axtend/axlib", default-features = false , branch = "c92f69d" }

frame-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
frame-try-runtime = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
pallet-offences-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
pallet-session-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
frame-system-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, optional = true , branch = "c92f69d" }
hex-literal = { version = "0.3.4", optional = true }

runtime-common = { package = "axia-runtime-common", path = "../common", default-features = false }
runtime-allychains = { package = "axia-runtime-allychains", path = "../allychains", default-features = false }
primitives = { package = "axia-primitives", path = "../../primitives", default-features = false }

xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm-builder = { package = "xcm-builder", path = "../../xcm/xcm-builder", default-features = false }

[dev-dependencies]
hex-literal = "0.3.4"
tiny-keccak = "2.0.2"
keyring = { package = "sp-keyring", git = "https://github.com/axtend/axlib", branch = "c92f69d" }
sp-trie = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }
separator = "0.4.1"
serde_json = "1.0.78"

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axtend/axlib", branch = "c92f69d" }

[features]
default = ["std"]
no_std = []
only-staking = []
std = [
	"authority-discovery-primitives/std",
	"bitvec/std",
	"primitives/std",
	"rustc-hex/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"tx-pool-api/std",
	"block-builder-api/std",
	"offchain-primitives/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"frame-executive/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-democracy/std",
	"pallet-gilt/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-nicks/std",
	"pallet-offences/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-society/std",
	"pallet-staking/std",
	"pallet-staking-reward-fn/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"pallet-vesting/std",
	"pallet-babe/std",
	"pallet-xcm/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"sp-version/std",
	"serde_derive",
	"serde/std",
	"log/std",
	"babe-primitives/std",
	"sp-session/std",
	"runtime-common/std",
	"runtime-allychains/std",
	"frame-try-runtime/std",
	"sp-npos-elections/std",
	"beefy-primitives/std",
	"axctest-runtime-constants/std",
	"pallet-mmr-primitives/std",
	"xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
	"frame-election-provider-support/std",
]
runtime-benchmarks = [
	"runtime-common/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"pallet-gilt/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-tips/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-offences-benchmarking",
	"pallet-session-benchmarking",
	"pallet-xcm/runtime-benchmarks",
	"frame-system-benchmarking",
	"hex-literal",
	"xcm-builder/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"runtime-allychains/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
	"frame-system/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-nicks/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"pallet-society/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-tips/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-babe/try-runtime",
	"runtime-common/try-runtime",
]
# When enabled, the runtime API will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime API exported functions
# in WASM.
disable-runtime-api = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]

# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []

runtime-metrics = ["runtime-allychains/runtime-metrics", "sp-io/with-tracing"]
