[package]
name = "axia-node-core-dispute-coordinator"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
tracing = "0.1.29"
parity-scale-codec = "2"
kvdb = "0.10.0"
thiserror = "1.0.30"
lru = "0.7.2"

axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }

sc-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }

[dev-dependencies]
kvdb-memorydb = "0.10.0"
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
assert_matches = "1.4.0"
test-helpers = { package = "axia-primitives-test-helpers", path = "../../../primitives/test-helpers" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
