[package]
name = "axia-node-core-provisioner"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
futures = "0.3.21"
tracing = "0.1.29"
thiserror = "1.0.30"
axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
futures-timer = "3.0.2"
rand = "0.8.4"

[dev-dependencies]
sp-application-crypto = { git = "https://github.com/axtend/axlib", branch = "axlib" }
sp-keystore = { git = "https://github.com/axtend/axlib", branch = "axlib" }
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "axia-primitives-test-helpers", path = "../../../primitives/test-helpers" }
