[package]
name = "axia-node-core-pvf-checker"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
thiserror = "1.0.30"
tracing = "0.1.29"

axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-primitives = { path = "../../../primitives" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-overseer = { path = "../../overseer" }

sp-keystore = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

[dev-dependencies]
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-keystore = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-keyring = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers"}
test-helpers = { package = "axia-primitives-test-helpers", path = "../../../primitives/test-helpers" }
sp-application-crypto = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
futures-timer = "3.0.2"
