name: Send new release notification to matrix channels
on:
  release:
    types:
      - published

jobs:
  ping_matrix:
    strategy:
      matrix:
        channel:
          - name: '#AxiaTestValidatorLounge:axia.builders'
            room: '!LhjZccBOqFNYKLdmbb:axia.builders'
            pre-releases: false
          - name: '#axctest-announcements:matrix.axia.io'
            room: '!FMwxpQnYhRCNDRsYGI:matrix.axia.io'
            pre-release: false
          - name: '#axiavalidatorlounge:web3.foundation'
            room: '!NZrbtteFeqYKCUGQtr:matrix.axia.io'
            pre-release: false
          - name: '#axia-announcements:matrix.axia.io'
            room: '!UqHPWiCBGZWxrmYBkF:matrix.axia.io'
            pre-release: false
          - name: Internal release-notes channel
            room: '!NTogofoetwjbTwOoPi:matrix.axia.io'
            pre-release: true

    runs-on: ubuntu-latest
    steps:
      - name: Send Matrix message to ${{ matrix.channel.name }}
        if: github.event.release.prerelease == false || matrix.channel.pre-release
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ matrix.channel.room }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: "matrix.axia.io"
          message: "***Axia ${{github.event.release.tag_name}} has been released!***<br/>${{github.event.release.html_url}}<br/><br/>${{github.event.release.body}}<br/>"
